jobs:
stages:
  - name: Storage-Checker
    steps:
      - name: Storage-Checker_script
        image: ghcr.io/sushrut1101/docker:arch
        cpu: 4
        memory: 16G
        commands:
          - df -h
          - lsblk
          - ls -l -a -h

  - name: Sync
    steps:
      - name: Sync_script
        image: ghcr.io/sushrut1101/docker:arch
        cpu: 4
        memory: 16G
        commands:
          - echo "============================"
          - echo "Syncing The Sources..."
          - echo "============================"
          - mkdir -p ~/work
          - cd ~/work
          - repo init --depth=1 -u --no-repo-verify https://github.com/AICP/platform_manifest.git -b t13.0 --git-lfs
          - repo sync -j4 --force-sync --no-tags --no-clone-bundle
          - git clone https://github.com/zaidannn7/local_manifest --depth 1 -b aicp13 .repo/local_manifests
          - echo "============================"
          - echo "Syncing Complete!"
          - echo "============================"

  - name: Build
    steps:
      - name: Build_script
        image: ghcr.io/sushrut1101/docker:arch
        cpu: 4
        memory: 16G
        commands:
          - echo "============================"
          - echo "Starting the Build..."
          - echo "============================"
          - cd ~/work
          - $EXTRA_CMD
          - export USE_CCACHE=1
          - export CCACHE_EXEC=/usr/bin/ccache
          - ccache -M 50G
          - . build/envsetup.sh
          - lunch aicp_lime-userdebug
          - mka -j4 bacon

  - name: Upload
    steps:
      - name: Upload_script
        image: ghcr.io/sushrut1101/docker:arch
        cpu: 4
        memory: 16G
        commands:
          - echo "============================"
          - echo "Uploading the Build..."
          - echo "============================"
          - cd ~/work
          - cd out/target/product/lime
          - ls -lh
          - pwd
          - chmod 777 *
          - curl --upload-file $(echo *.zip) https://transfer.sh | tee link.txt && echo " "
          - echo " "
          - echo "============================"
          - echo "Build Uploaded!"
          - echo "Please see the link Below-  "
          - echo "----------------------------"
          - cat link.txt && echo " "
